title: Stine-Gill Wedding
email: king2bgill+weddingsite@gmail.com
url: https://www.stinegillwedding.us
enforce_ssl: www.stinegillwedding.us
github_username: johnsgill3
description: >
    Information about the wedding of John Gill & Rachel Stine
